global:
  scrape_interval: 5s          # 메트릭 수집 주기
  evaluation_interval: 5s      # 룰 평가 주기

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - app:8081