spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/party?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: ""   # 필요하면 입력
      timeout: 2000ms

app:
  domain:
    base: ${LOCAL_DOMAIN_BASE}

jwt:
  access-exp: 2592000000
  refresh-exp: 2592000000  # 30일


# trace - debug - info - warn - error
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO