spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${PROD_DATABASE_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT:6379}
      password: ${PROD_REDIS_PASSWORD:}   # 없으면 빈 값

app:
  domain:
    base: ${PROD_DOMAIN_BASE}

logging:
  level:
    root: info