spring:
  application:
    name: partyguham

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  security:
    user:
      name: admin
      password: 1234

server:
  port: ${PORT}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET}
  issuer: partyguham
  access-exp: 900000
  refresh-exp: 1209600000  # 14Ïùº
  header: Authorization
  prefix: Bearer

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri:
      login: http://localhost:8081/api/v2/auth/oauth/kakao/login/callback
      link: http://localhost:8081/api/v2/auth/oauth/kakao/link/callback
    auth-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    userinfo-uri: https://kapi.kakao.com/v2/user/me
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri:
      login: http://localhost:8081/api/v2/auth/oauth/google/login/callback
      link: http://localhost:8081/api/v2/auth/oauth/google/link/callback
    auth-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    userinfo-uri: https://www.googleapis.com/oauth2/v3/userinfo

aws:
  s3:
    bucket: ${S3_BUCKET}
    region: ap-northeast-2
    base-folder: images
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

firebase:
  service-account:
    path: ${FIREBASE_KEY_PATH}
