spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DEV_DATABASE_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}   # 없으면 빈 값

app:
  domain:
    base: ${DEV_DOMAIN_BASE}

logging:
  level:
    root: debug